# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- service.yaml

patches:
  - path: deployment.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
