# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
- ../base

patches:
  - path: deployment.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/requests/ephemeral-storage
    target:
      kind: Deployment
