# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../lmcache

patches:
- options:
    allowNameChange: true
  path: deployment.patch.yaml
  target:
    kind: Deployment
- options:
    allowNameChange: true
  path: service.patch.yaml
  target:
    kind: Service
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --tensor-parallel-size=8
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value: 
        name: LMCACHE_MAX_LOCAL_CPU_SIZE
        value: "128.0"
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: 1024G
  target:
    kind: Deployment
