apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-request: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
    spec:
      containers:
      - name: inference-server
        env:
          - name: MODEL_PATH
            value: path/to/model
            valueFrom:
              $patch: delete
      volumes:
      - name: gke-gcsfuse-cache
        emptyDir:
          medium: Memory
        
