# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../lmcache/local-cpu

components:
  - ../../../../../components/gke/resources/gpu/8-H100-80GB-MEGA
  # - ../../../components/hpa/vllm/token-latency # HPA is a work-in-progress

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
  - options:
      allowNameChange: true
    path: hpa.patch.yaml
    target:
      kind: HorizontalPodAutoscaler
