apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: llama3-405b-lws
spec:
  leaderWorkerTemplate:
    size: 2
    leaderTemplate:
      metadata:
        labels:
          ai.gke.io/model: llama3-405b
    workerTemplate:
      metadata:
        labels:
          ai.gke.io/model: llama3-405b
